#!/bin/bash
# VS Code 快速启动脚本

echo "=================================="
echo "🚀 OpenFang Auto Clip - 启动选项"
echo "=================================="
echo ""
echo "请选择要运行的功能："
echo ""
echo "1️⃣  生成IP角色（消防员小狗 Spike）"
echo "   命令: python3 generate_ip_character.py"
echo ""
echo "2️⃣  打开IP角色测试页面（浏览器）"
echo "   命令: open ~/.openfang/ip_characters/test.html"
echo ""
echo "3️⃣  测试版权转换效果"
echo "   命令: python3 test_transform.py"
echo ""
echo "4️⃣  Level 3 完全重制（生成项目包）"
echo "   命令: python3 level3_recreator.py"
echo ""
echo "5️⃣  处理YouTube视频"
echo "   命令: python3 auto_clip.py \"视频URL\" --transform 1"
echo ""
echo "=================================="
echo ""
echo "💡 推荐从选项1开始！"
echo ""
echo "在VS Code终端中复制粘贴上面的命令即可运行。"
